# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4377b72efca76cab283e811d8348d8fa766695b862c5fa373da9fcac2b8c0edd4752e86df34012d1023a74b2fc7727d5ab72615f488148b49573e6b236469180

test:
  secret_key_base: 208cb9c6ace0139ada88f94423943a792d9c614ce871426389771ffa201a98df8fca44e3bd07d3d26f3754a3f93f6d3d2c82162d8b04ed8b2dc4ebefdaf1815e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
